# Generated by Django 4.1.3 on 2022-11-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('Branch', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('PassOutYear', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('college_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alum.collegeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PastCompanies_AndPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position_hold', models.CharField(blank=True, max_length=100, null=True)),
                ('years_worked', models.CharField(max_length=10)),
                ('college_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alum.collegeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Current_WorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('current_position', models.CharField(max_length=100)),
                ('years_worked', models.CharField(max_length=10)),
                ('college_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alum.collegeprofile')),
            ],
            options={
                'db_table': 'current_workprofile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConnectHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handlename', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('college_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alum.collegeprofile')),
            ],
        ),
    ]
